site_name: MinExilon
site_url: https://beta.minexilon.com/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.blocks.html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/logo_minexilon_cube.png
  favicon: assets/logo_minexilon_favicon.ico
  font:
    text: Saira
  palette:
    - scheme: default
      toggle:
        icon: material/minecraft
        name: Cambia al modo oscuro
      primary: custom
      accent: pink
    - scheme: slate
      toggle:
        icon: material/cube
        name: Cambia al modo claro
      primary: custom
      accent: pink
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - announce.dismiss
    - content.tooltips
    - content.code.copy
extra_css:
  - stylesheets/extra.css
  - stylesheets/tags-econ.css
  - stylesheets/tags-rank.css
  - stylesheets/tags-tier.css
  - stylesheets/lucide.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Novedades
        - Eventos
        - Festividades
        - Temporadas
        - Ciudades
        - Tutoriales
      pagination_per_page: 5
  - tags
  - meta
nav:
  - Inicio: index.md
  - Blog:
    - blog/index.md
  - Wiki:
    - wiki/index.md
    - Introductorios:
      - Cómo empezar: wiki/basico/como-empezar.md
      - Rangos del servidor: wiki/basico/rangos.md
      - Cómo votar: wiki/basico/votar.md
      - Preguntas frequentes: wiki/basico/faq.md
    - Generales:
      - Trabajos: wiki/general/jobs.md
      - Pesca: wiki/general/pesca.md
      - Bebidas: wiki/general/bebidas.md
      - Mundo Creativo: wiki/general/creativo.md
    - Economía:
      - Zona Ágora: wiki/economia/agora.md
      - Subastas: wiki/economia/subastas.md
    - Ciudades:
      - Comandos: wiki/ciudades/comandos.md
      - Buen Alcalde: wiki/ciudades/buen-alcalde.md
      - Desahucios: wiki/ciudades/desahucios.md
    - Eventos:
      - Temporadas: wiki/eventos/temporadas.md
      - Especiales: wiki/eventos/especiales.md
      - Minijuegos: wiki/eventos/minijuegos.md
  - Normativa: normativa.md
  - Mapa: https://mapa.minexilon.com/
  - Tienda: https://store.minexilon.com/
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fxEqfnT
      name: Servidor de Discord
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/minexilon
      name: Canal de Twitch
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCRhbX5mSyo_zLm2GQS4Rpqw
      name: Canal de YouTube
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/minexilon_server/
      name: Perfil de Instagram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/minexilon
      name: Perfil de Twitter
  status:
    new: Actualizado
    deprecated: Obsoleto
  consent:
    title: Consentimiento de galletas (cookies)
    description: >- 
      Usamos cookies para reconocer tus visitas y preferencias,
      así como para medir la efectividad de la página y si los
      usuarios encuentran lo que buscan.
      Con tu consentimiento, nos ayudas a mejorar la página.
    actions:
      - accept
      - manage
      - reject
  generator: false
copyright: > 
  Copyright &copy; 2018 - 2025 MinExilon.
  <a href="#__consent">Ajuste de cookies.</a> <br>
  <a href="/terminos-condiciones/">Privacidad, Términos y Condiciones de servicio.</a>